export const DAILY_PROMPTS: string[] = [
  // Mindfulness & Grounding
  "DASHBOARD.PROMPTS.P1",
  "DASHBOARD.PROMPTS.P2",
  "DASHBOARD.PROMPTS.P3",
  "DASHBOARD.PROMPTS.P4",
  "DASHBOARD.PROMPTS.P5",
  "DASHBOARD.PROMPTS.P6",
  
  // Gratitude & Positivity
  "DASHBOARD.PROMPTS.P7",
  "DASHBOARD.PROMPTS.P8",
  "DASHBOARD.PROMPTS.P9",
  "DASHBOARD.PROMPTS.P10",
  "DASHBOARD.PROMPTS.P11",
  
  // Self-Compassion
  "DASHBOARD.PROMPTS.P12",
  "DASHBOARD.PROMPTS.P13",
  "DASHBOARD.PROMPTS.P14",
  "DASHBOARD.PROMPTS.P15",
  "DASHBOARD.PROMPTS.P16",
  
  // Reflection
  "DASHBOARD.PROMPTS.P17",
  "DASHBOARD.PROMPTS.P18",
  "DASHBOARD.PROMPTS.P19",
  "DASHBOARD.PROMPTS.P20",
  
  // Extra Variety
  "DASHBOARD.PROMPTS.P21",
  "DASHBOARD.PROMPTS.P22",
  "DASHBOARD.PROMPTS.P23",
  "DASHBOARD.PROMPTS.P24",
  "DASHBOARD.PROMPTS.P25",
  "DASHBOARD.PROMPTS.P26",
  "DASHBOARD.PROMPTS.P27",
  "DASHBOARD.PROMPTS.P28",
  "DASHBOARD.PROMPTS.P29",
  "DASHBOARD.PROMPTS.P30"
];